/**
 * Writes SCRIPT.md from the same data the film was cut from, with the timecodes
 * measured off the finished clips. Hand-maintained timings go stale the first
 * time a line of narration changes; these cannot.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { ASPECTS, ILLUSTRATIVE_NOTICE, OUT_DIR, PKG_ROOT, type AspectSpec } from './brand.js';
import { scenesFor } from './narration.js';
import { loadVoice } from './voice.js';
import { ffprobeDuration } from './ffmpeg.js';
import { RATE, VOICE } from './voice.js';

const tc = (s: number) => {
  const m = Math.floor(s / 60);
  const sec = s - m * 60;
  return `${m}:${sec.toFixed(1).padStart(4, '0')}`;
};

async function cutSection(cut: AspectSpec['key']): Promise<string> {
  const scenes = scenesFor(cut);
  const vo = await loadVoice();
  const lines: string[] = [];
  let at = 0;

  lines.push(`### ${cut === 'landscape' ? '16:9 — the long cut' : '9:16 — the short cut'}\n`);
  lines.push('| In | Out | Scene | On screen | Narration |');
  lines.push('|---|---|---|---|---|');

  for (const scene of scenes) {
    const file = path.join(OUT_DIR, cut, `${scene.id}.mp4`);
    const dur = await ffprobeDuration(file).catch(() => 0);
    const caption = scene.caption + (scene.illustrative ? ' *(+ illustrative-figures notice)*' : '');
    lines.push(
      `| ${tc(at)} | ${tc(at + dur)} | \`${scene.id}\` | ${caption} | ${scene.vo} |`,
    );
    at += dur;
  }

  const ident = (process.env.PROMO_IDENT ?? 'landscape').split(',').includes(cut);
  if (ident) {
    lines.push(`| ${tc(at)} | ${tc(at + 11.97)} | \`ident\` | — | *(brand ident, silent)* |`);
    at += 11.97;
  }
  lines.push(`\n**Total ${tc(at)}.** Narration ${vo.filter((c) => scenes.some((s) => s.id === c.id)).reduce((a, c) => a + c.seconds, 0).toFixed(1)}s.\n`);
  return lines.join('\n');
}

export async function writeScriptDoc(): Promise<string> {
  const body = `# Partner Portal promo — shot list and narration

Generated by \`npm run docs\` in \`tools/promo-video\`. Timecodes are measured off
the rendered clips, not estimated.

**Voice** \`${VOICE}\` at ${RATE} wpm (macOS \`say\`). To re-record with a human
voice, use the narration column below — each line is timed to its own scene, so
a replacement take should be cut to the same in/out points.

**Footage** is the real Partner Portal, driven live in Chromium against the demo
partner account (\`NIYOM1234D\`). Every client, security, statement and figure on
screen is invented; the portal's own "Sample portal" banner is visible
throughout, and scenes showing money additionally carry:

> ${ILLUSTRATIVE_NOTICE}

**Aspect ratios** — ${ASPECTS.landscape.width}×${ASPECTS.landscape.height} and
${ASPECTS.vertical.width}×${ASPECTS.vertical.height}. The vertical cut is filmed
at the portal's own phone layout, not a scaled-down desktop.

---

${await cutSection('landscape')}
---

${await cutSection('vertical')}
---

## Re-cutting

| Want to | Do |
|---|---|
| Change a line | Edit \`src/narration.ts\`, then \`npm run all\` |
| Re-shoot one scene | \`PROMO_ONLY=bonds npm run capture -- landscape\`, then \`npm run build\` |
| Use a better voice | Download an Enhanced voice in System Settings → Accessibility → Spoken Content → Manage Voices, then \`PROMO_VOICE="Ava (Premium)" npm run all\` |
| Add the ident to the vertical cut | \`PROMO_IDENT=landscape,vertical npm run build\` |
| Add music | Drop an mp3 in \`audio/\` — currently unmixed; no licensed track ships with the repo |
`;

  const file = path.join(PKG_ROOT, 'SCRIPT.md');
  await fs.writeFile(file, body);
  return file;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  console.log(`wrote ${await writeScriptDoc()}`);
}
