import { useState } from 'react';
import { Wallet, Download, FileText, Loader2 } from 'lucide-react';
import { Card } from '../../../portal/components/Card';
import { KpiStat } from '../../../portal/components/KpiStat';
import { SectionHeader } from '../../../portal/components/SectionHeader';
import { StatusPill } from '../../../portal/components/StatusPill';
import { EmptyState } from '../../../portal/components/EmptyState';
import { fmt } from '../../../crm/utils';
import { PartnerService } from '../../services/PartnerService';
import type { PartnerDebitNote, PartnerPayoutSummary } from '../../types';

interface Props {
  payout: PartnerPayoutSummary | null;
  notes: PartnerDebitNote[];
}

const MONTHS = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

const statusTone = (s: string) =>
  s === 'paid' ? 'success' : s === 'cancelled' ? 'danger' : 'warning';

const signatureTone = (s: string) =>
  s === 'signed' ? 'success' : s === 'not_sent' ? 'muted' : 'info';

/**
 * Payout statements. Every figure here is read straight from a debit note that
 * has already been raised and frozen (signed notes are immutable per migration
 * 20260625120300, and carry a pdf_snapshot). The payout formula itself is NOT
 * reimplemented — it lives solely in src/crm/DSAPayout.tsx, and a second copy
 * would eventually disagree with the document the partner signed.
 */
export function PayoutsPage({ payout, notes }: Props) {
  const [busyId, setBusyId] = useState<string | null>(null);

  const openStatement = async (note: PartnerDebitNote) => {
    const path = note.signed_pdf_url || note.pdf_url;
    if (!path) return;
    setBusyId(note.id);
    const url = await PartnerService.getStatementUrl(path);
    setBusyId(null);
    if (url) window.open(url, '_blank', 'noopener,noreferrer');
  };

  const exportCsv = () => {
    const header = ['Statement', 'Period', 'Gross', 'TDS', 'Net Payable', 'Status', 'Signature', 'Paid On'];
    const rows = notes.map((n) => [
      n.debit_note_number,
      `${MONTHS[n.month]} ${n.year}`,
      n.payout_amount,
      n.tds_amount,
      n.net_payable_amount,
      n.status,
      n.signature_status,
      n.paid_at ? new Date(n.paid_at).toLocaleDateString('en-IN') : '',
    ]);
    const csv = [header, ...rows]
      .map((r) => r.map((c) => `"${String(c ?? '').replace(/"/g, '""')}"`).join(','))
      .join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `niyom-payout-statements-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card>
        <SectionHeader title={`Financial Year ${payout?.fy_label ?? ''}`} icon={Wallet} />
        <div className="mt-5 grid grid-cols-2 gap-6 lg:grid-cols-4">
          <KpiStat label="Gross raised" value={fmt(Number(payout?.fy_gross ?? 0))} sub="Before TDS" />
          <KpiStat label="TDS deducted" value={fmt(Number(payout?.fy_tds ?? 0))} sub="At 2%" />
          <KpiStat label="Net raised" value={fmt(Number(payout?.fy_net ?? 0))} color="var(--accent)" />
          <KpiStat
            label="Paid to date"
            value={fmt(Number(payout?.paid_net ?? 0))}
            color="var(--success)"
            sub="All years, net"
            trend="up"
          />
        </div>
        <p className="mt-5 border-t border-border-subtle pt-4 text-xs text-text-faint">
          Figures are taken from the statements already raised for you. A month appears
          here once its statement has been generated by Niyom Wealth.
        </p>
      </Card>

      <Card padding="none">
        <div className="flex items-center justify-between gap-3 border-b border-border-subtle p-5">
          <div className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-accent" />
            <h3 className="text-sm font-bold text-text-primary">Statements</h3>
          </div>
          {notes.length > 0 && (
            <button
              type="button"
              onClick={exportCsv}
              className="flex items-center gap-1.5 rounded-token-md border border-border bg-bg-surface px-3 py-1.5 text-xs font-semibold text-text-primary transition-colors hover:text-accent"
            >
              <Download className="h-3.5 w-3.5" /> Export CSV
            </button>
          )}
        </div>

        {notes.length === 0 ? (
          <EmptyState
            icon={FileText}
            title="No statements yet"
            hint="Your monthly payout statements will appear here once raised."
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px] text-sm">
              <thead>
                <tr className="border-b border-border-subtle text-[11px] uppercase tracking-wider text-text-faint">
                  <th className="px-5 py-3 text-left font-semibold">Statement</th>
                  <th className="px-5 py-3 text-left font-semibold">Period</th>
                  <th className="px-5 py-3 text-right font-semibold">Gross</th>
                  <th className="px-5 py-3 text-right font-semibold">TDS</th>
                  <th className="px-5 py-3 text-right font-semibold">Net Payable</th>
                  <th className="px-5 py-3 text-left font-semibold">Status</th>
                  <th className="px-5 py-3 text-right font-semibold">PDF</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border-subtle">
                {notes.map((n) => (
                  <tr key={n.id} className="transition-colors hover:bg-hover">
                    <td className="px-5 py-3 font-mono text-xs text-text-primary">
                      {n.debit_note_number}
                    </td>
                    <td className="px-5 py-3 text-text-secondary">
                      {MONTHS[n.month]} {n.year}
                    </td>
                    <td className="px-5 py-3 text-right tabular-nums text-text-secondary">
                      {fmt(Number(n.payout_amount))}
                    </td>
                    <td className="px-5 py-3 text-right tabular-nums text-text-secondary">
                      {fmt(Number(n.tds_amount))}
                    </td>
                    <td className="px-5 py-3 text-right tabular-nums font-semibold text-text-primary">
                      {fmt(Number(n.net_payable_amount))}
                    </td>
                    <td className="px-5 py-3">
                      <div className="flex flex-wrap gap-1.5">
                        <StatusPill tone={statusTone(n.status)}>{n.status}</StatusPill>
                        <StatusPill tone={signatureTone(n.signature_status)}>
                          {n.signature_status.replace(/_/g, ' ')}
                        </StatusPill>
                      </div>
                    </td>
                    <td className="px-5 py-3 text-right">
                      {n.signed_pdf_url || n.pdf_url ? (
                        <button
                          type="button"
                          onClick={() => openStatement(n)}
                          disabled={busyId === n.id}
                          className="inline-flex items-center gap-1.5 rounded-token-md border border-border bg-bg-surface px-2.5 py-1.5 text-xs font-semibold text-text-primary transition-colors hover:text-accent disabled:opacity-50"
                        >
                          {busyId === n.id ? (
                            <Loader2 className="h-3.5 w-3.5 animate-spin" />
                          ) : (
                            <Download className="h-3.5 w-3.5" />
                          )}
                          {n.signed_pdf_url ? 'Signed' : 'Open'}
                        </button>
                      ) : (
                        <span className="text-xs text-text-faint">—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
