/*
  # 4-digit sign-in PIN, bound to a remembered device

  A PIN is a convenience credential, not a password: four digits is ten
  thousand combinations, which is nothing against an attacker who can guess
  freely. Everything that makes it safe lives here and in the three edge
  functions that own this table:

    - it only works on a device that completed a FULL login (password or
      Google) and registered itself, so the PIN alone is never enough;
    - the server counts attempts and locks the device, because a browser
      cannot be trusted to count its own failures;
    - it expires, and the client can revoke any device from Profile → Settings.

  ## Why no RLS policies

  Deliberate: there are none, so the table is unreachable with an anon or
  authenticated key and only the service role (the edge functions) can touch
  it. The alternative — letting a client read their own rows — would put
  `pin_hash` one `select *` away from the browser for no benefit, since the
  device list they see is served by an edge function anyway.
*/

CREATE TABLE IF NOT EXISTS nw_client_device_pins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL REFERENCES nw_clients(id) ON DELETE CASCADE,
  /* Opaque random id generated by the browser and kept in localStorage. It
     names the device; it proves nothing on its own. */
  device_id text NOT NULL,
  /* "Chrome on macOS" — for the revoke list, so a client can tell devices
     apart. Browser-supplied and therefore untrusted: display only. */
  device_label text,
  /* PBKDF2-SHA256. The PIN itself is never stored, logged or returned. */
  pin_hash text NOT NULL,
  pin_salt text NOT NULL,
  pin_iterations int NOT NULL,
  failed_attempts int NOT NULL DEFAULT 0,
  /* Set while cooling off after consecutive failures. */
  locked_until timestamptz,
  /* Set when the PIN is burned after too many failures, or revoked by the
     client. A revoked row is kept so the device list can still show it. */
  revoked_at timestamptz,
  expires_at timestamptz NOT NULL,
  last_used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  /* One PIN per device per client — setting a new one replaces the old. */
  UNIQUE (client_id, device_id)
);

COMMENT ON TABLE nw_client_device_pins IS
  'Per-device 4-digit sign-in PINs for the client portal. Service-role only (no RLS policies); see client-pin-* edge functions.';

/* The login path looks a device up by its id alone, before it knows the client. */
CREATE INDEX IF NOT EXISTS idx_client_device_pins_device ON nw_client_device_pins(device_id);
CREATE INDEX IF NOT EXISTS idx_client_device_pins_client ON nw_client_device_pins(client_id);

ALTER TABLE nw_client_device_pins ENABLE ROW LEVEL SECURITY;
/* No policies on purpose — see the header. */

CREATE OR REPLACE FUNCTION nw_client_device_pins_touch()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_nw_client_device_pins_touch ON nw_client_device_pins;
CREATE TRIGGER trg_nw_client_device_pins_touch
  BEFORE UPDATE ON nw_client_device_pins
  FOR EACH ROW EXECUTE FUNCTION nw_client_device_pins_touch();
