/*
  # Marketing Tool — employee referral links, click tracking, lead attribution

  Every employee gets a unique, permanent onboarding URL:

      https://www.niyomwealth.com/onboarding?ref=<ref_code>

  Captions generated by the Content Creation module carry a {{REF_LINK}}
  placeholder; when an employee copies a caption the placeholder is replaced with
  THEIR link. A signup arriving through that link is assigned to that employee
  instead of the default house account, and the click -> lead -> client funnel is
  recorded for the admin analytics dashboard.

  ## Why an opaque random code (not employee_code)
  The ref code appears in public social captions. employee_code ("NIYOM-001") is
  sequential and doubles as the client-code prefix, so publishing it would leak
  headcount and let anyone enumerate staff. A short random code carries the same
  information for us and none of it for the public. mkt_referral_links is the
  resolver, so the code scheme can change later without touching any caller.

  ## Onboarding behaviour is unchanged when there is no ref
  The onboarding edge functions resolve the code defensively: unknown, inactive
  or absent -> fall back to the existing default employee and the existing
  admin-pool lead. Nothing about the current flow changes for direct signups.

  ## Safety
  Idempotent and additive. nw_employees gains no columns; the provisioning
  trigger is SECURITY DEFINER and never SELECTs nw_employees (that table is FORCE
  RLS and has a history of policy recursion — see
  20260727180000_fix_nw_employees_update_recursion.sql).
*/

-- ---------------------------------------------------------------------------
-- 1. Referral code generator — 8 chars, unambiguous alphabet (no 0/O/1/l/i).
--    Retries on the (astronomically unlikely) unique collision.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION mkt_generate_ref_code()
RETURNS text LANGUAGE plpgsql VOLATILE SET search_path = public AS $$
DECLARE
  v_alphabet constant text := 'abcdefghjkmnpqrstuvwxyz23456789';
  v_code text;
  v_i    integer;
BEGIN
  LOOP
    v_code := '';
    FOR v_i IN 1..8 LOOP
      v_code := v_code || substr(v_alphabet, floor(random() * length(v_alphabet))::int + 1, 1);
    END LOOP;
    EXIT WHEN NOT EXISTS (SELECT 1 FROM mkt_referral_links WHERE ref_code = v_code);
  END LOOP;
  RETURN v_code;
END;
$$;

-- ---------------------------------------------------------------------------
-- 2. One link per employee
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mkt_referral_links (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id uuid UNIQUE NOT NULL REFERENCES nw_employees(id) ON DELETE CASCADE,
  ref_code    text UNIQUE NOT NULL DEFAULT mkt_generate_ref_code(),
  active      boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mkt_referral_links_code ON mkt_referral_links (ref_code) WHERE active;

-- Backfill for everyone who already works here. Row-by-row on purpose: the
-- collision check inside mkt_generate_ref_code() cannot see rows written by its
-- own INSERT statement, so a set-based backfill could only self-deduplicate by
-- luck. Separate statements make each generated code visible to the next.
DO $$
DECLARE
  v_emp uuid;
BEGIN
  FOR v_emp IN SELECT id FROM nw_employees WHERE status = 'active' LOOP
    INSERT INTO mkt_referral_links (employee_id)
    VALUES (v_emp)
    ON CONFLICT (employee_id) DO NOTHING;
  END LOOP;
END $$;

-- New hires get one automatically. SECURITY DEFINER because create-crm-user
-- inserts via the service role and mkt_referral_links has no client INSERT
-- policy; the function deliberately does not read nw_employees.
CREATE OR REPLACE FUNCTION mkt_provision_referral_link()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO mkt_referral_links (employee_id)
  VALUES (NEW.id)
  ON CONFLICT (employee_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mkt_referral_link ON nw_employees;
CREATE TRIGGER trg_mkt_referral_link
  AFTER INSERT ON nw_employees
  FOR EACH ROW EXECUTE FUNCTION mkt_provision_referral_link();

-- ---------------------------------------------------------------------------
-- 3. Click tracking. Written only by the public mkt-track-click edge function
--    (service role), which hashes the IP before it ever reaches this table.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mkt_referral_clicks (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ref_code    text NOT NULL,
  employee_id uuid REFERENCES nw_employees(id) ON DELETE SET NULL,
  content_no  text,
  platform    text NOT NULL DEFAULT '',
  ip_hash     text NOT NULL DEFAULT '',
  user_agent  text NOT NULL DEFAULT '',
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mkt_clicks_ref      ON mkt_referral_clicks (ref_code, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mkt_clicks_ip       ON mkt_referral_clicks (ip_hash, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mkt_clicks_employee ON mkt_referral_clicks (employee_id);
CREATE INDEX IF NOT EXISTS idx_mkt_clicks_content  ON mkt_referral_clicks (content_no);

-- ---------------------------------------------------------------------------
-- 4. Attribution — which employee/content/platform brought this client in.
--    Written by the onboarding edge functions (service role).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mkt_lead_attributions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id       uuid REFERENCES nw_clients(id) ON DELETE SET NULL,
  lead_id         uuid REFERENCES nw_leads(id)   ON DELETE SET NULL,
  employee_id     uuid NOT NULL REFERENCES nw_employees(id) ON DELETE CASCADE,
  ref_code        text NOT NULL,
  content_no      text,
  platform        text NOT NULL DEFAULT '',
  campaign_source text NOT NULL DEFAULT 'marketing_content',
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mkt_attr_client   ON mkt_lead_attributions (client_id);
CREATE INDEX IF NOT EXISTS idx_mkt_attr_lead     ON mkt_lead_attributions (lead_id);
CREATE INDEX IF NOT EXISTS idx_mkt_attr_employee ON mkt_lead_attributions (employee_id);
CREATE INDEX IF NOT EXISTS idx_mkt_attr_content  ON mkt_lead_attributions (content_no);

-- ---------------------------------------------------------------------------
-- 5. RLS
-- ---------------------------------------------------------------------------
ALTER TABLE mkt_referral_links    ENABLE ROW LEVEL SECURITY;
ALTER TABLE mkt_referral_clicks   ENABLE ROW LEVEL SECURITY;
ALTER TABLE mkt_lead_attributions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Employees read own referral link" ON mkt_referral_links;
DROP POLICY IF EXISTS "Admins read referral clicks"      ON mkt_referral_clicks;
DROP POLICY IF EXISTS "Admins read lead attributions"    ON mkt_lead_attributions;

-- An employee needs their own code to build the link they paste into captions.
CREATE POLICY "Employees read own referral link"
  ON mkt_referral_links FOR SELECT TO authenticated
  USING (employee_id = nw_current_employee_id() OR nw_current_emp_is_admin());

-- Analytics tables: admin read only. All writes are service-role.
CREATE POLICY "Admins read referral clicks"
  ON mkt_referral_clicks FOR SELECT TO authenticated
  USING (nw_current_emp_is_admin());

CREATE POLICY "Admins read lead attributions"
  ON mkt_lead_attributions FOR SELECT TO authenticated
  USING (nw_current_emp_is_admin());
