/*
  # Rebuild public-content tables (Learning / News / MF Research)

  Full teardown + clean recreate of the three tables that back the public
  marketing pages, as part of the 2026-07-24 rebuild of the Learning, News,
  MF Research and Calculator pages. (Calculator is client-side and has no
  backend.)

  ## Destructive
  Drops and recreates `news`, `mutual_funds`, and `commodity_prices`. Existing
  rows are ERASED — all of this data is synthetic and regenerated by the
  `fetch-financial-news`, `update-mutual-funds`, and `update-commodity-prices`
  edge functions.

  ## What this migration does
  1. Removes the `delete-old-news-daily` cron job and `delete_old_news()` fn.
  2. Drops the three tables (CASCADE clears their policies/indexes).
  3. Recreates each table with RLS, public read policies, service-role write
     policies, and the indexes the pages rely on.
  4. Recreates `delete_old_news()` (search_path-pinned, SECURITY DEFINER) and
     re-schedules the daily cleanup when pg_cron is available.

  ## Security model (unchanged intent)
  - Public/anon SELECT — this is non-PII educational/marketing data.
  - INSERT/UPDATE restricted to the service role (edge functions).
*/

-- ---------------------------------------------------------------------------
-- 1. Tear down old cron job + function (guarded; pg_cron may not be present)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'cron') THEN
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'delete-old-news-daily') THEN
      PERFORM cron.unschedule('delete-old-news-daily');
    END IF;
  END IF;
END $$;

DROP FUNCTION IF EXISTS delete_old_news();

-- ---------------------------------------------------------------------------
-- 2. Drop tables
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS news CASCADE;
DROP TABLE IF EXISTS mutual_funds CASCADE;
DROP TABLE IF EXISTS commodity_prices CASCADE;

-- ---------------------------------------------------------------------------
-- 3a. news
-- ---------------------------------------------------------------------------
CREATE TABLE news (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title         text NOT NULL,
  description   text,
  content       text,
  url           text,
  image_url     text,
  source        text,
  category      text DEFAULT 'general',
  published_at  timestamptz DEFAULT now(),
  created_at    timestamptz DEFAULT now()
);

ALTER TABLE news ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read news"
  ON news FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Service role can insert news"
  ON news FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "Service role can update news"
  ON news FOR UPDATE TO service_role USING (true) WITH CHECK (true);

CREATE INDEX news_published_at_idx ON news (published_at DESC);
CREATE INDEX news_category_idx     ON news (category);
CREATE INDEX news_url_idx          ON news (url);

-- ---------------------------------------------------------------------------
-- 3b. mutual_funds
-- ---------------------------------------------------------------------------
CREATE TABLE mutual_funds (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fund_name      text NOT NULL,
  fund_code      text UNIQUE,
  category       text DEFAULT 'Equity',
  sub_category   text,
  aum            numeric DEFAULT 0,
  expense_ratio  numeric DEFAULT 0,
  return_1y      numeric DEFAULT 0,
  return_3y      numeric DEFAULT 0,
  return_5y      numeric DEFAULT 0,
  launch_date    date,
  risk_level     text DEFAULT 'Moderate',
  min_investment numeric DEFAULT 500,
  fund_manager   text,
  updated_at     timestamptz DEFAULT now(),
  created_at     timestamptz DEFAULT now()
);

ALTER TABLE mutual_funds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read mutual funds"
  ON mutual_funds FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Service role can insert mutual funds"
  ON mutual_funds FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "Service role can update mutual funds"
  ON mutual_funds FOR UPDATE TO service_role USING (true) WITH CHECK (true);

CREATE INDEX mutual_funds_category_idx  ON mutual_funds (category);
CREATE INDEX mutual_funds_return_1y_idx ON mutual_funds (return_1y DESC);
CREATE INDEX mutual_funds_fund_code_idx ON mutual_funds (fund_code);

-- ---------------------------------------------------------------------------
-- 3c. commodity_prices
-- ---------------------------------------------------------------------------
CREATE TABLE commodity_prices (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  commodity   text NOT NULL CHECK (commodity IN ('gold', 'silver')),
  price       numeric NOT NULL,
  price_date  date NOT NULL,
  source      text NOT NULL DEFAULT 'MCX',
  created_at  timestamptz DEFAULT now(),
  UNIQUE (commodity, price_date)
);

ALTER TABLE commodity_prices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read commodity prices"
  ON commodity_prices FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Service role can insert commodity prices"
  ON commodity_prices FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "Service role can update commodity prices"
  ON commodity_prices FOR UPDATE TO service_role USING (true) WITH CHECK (true);

CREATE INDEX idx_commodity_prices_date      ON commodity_prices (price_date DESC);
CREATE INDEX idx_commodity_prices_commodity ON commodity_prices (commodity, price_date DESC);

-- ---------------------------------------------------------------------------
-- 4. Housekeeping: keep the news feed lean (delete articles older than 30 days)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION delete_old_news()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted_count integer;
BEGIN
  DELETE FROM news WHERE published_at < now() - INTERVAL '30 days';
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$;

-- Re-schedule the daily cleanup at 02:00 UTC when pg_cron is available.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'cron') THEN
    PERFORM cron.schedule('delete-old-news-daily', '0 2 * * *', 'SELECT delete_old_news();');
  END IF;
END $$;
